-- EXTENSÕES
-- Habilita extensão para gerar UUIDs (padrão no Supabase, mas bom garantir)
create extension if not exists "uuid-ossp";

-- -----------------------------------------------------------------------------
-- 1. TABELA PROFILES (Dados públicos/extras do usuário)
-- Vinculada automaticamente à tabela interna auth.users do Supabase
-- -----------------------------------------------------------------------------
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  subscription_status text check (subscription_status in ('trial', 'active', 'inactive')) default 'trial',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Segurança (RLS) para Profiles
alter table public.profiles enable row level security;

create policy "Usuários podem ver seu próprio perfil"
  on public.profiles for select
  using ( auth.uid() = id );

create policy "Usuários podem atualizar seu próprio perfil"
  on public.profiles for update
  using ( auth.uid() = id );

-- Trigger para criar profile automaticamente quando um user é criado no Auth (Opcional, mas recomendado)
-- create function public.handle_new_user()
-- returns trigger as $$
-- begin
--   insert into public.profiles (id, full_name)
--   values (new.id, new.raw_user_meta_data->>'full_name');
--   return new;
-- end;
-- $$ language plpgsql security definer;
-- create trigger on_auth_user_created
--   after insert on auth.users
--   for each row execute procedure public.handle_new_user();


-- -----------------------------------------------------------------------------
-- 2. TABELA LOCATIONS (Normalização Geográfica)
-- -----------------------------------------------------------------------------
create table public.locations (
  id bigint generated by default as identity primary key,
  city text not null,
  region text, -- Ex: Zona Sul, Centro
  neighborhood text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(city, neighborhood) -- Evita duplicatas
);

-- Segurança (RLS) para Locations
alter table public.locations enable row level security;

create policy "Locais são públicos para leitura"
  on public.locations for select
  to authenticated
  using ( true );

-- Apenas service_role (backend) pode inserir/editar (Nenhuma policy de write para anon/authenticated)


-- -----------------------------------------------------------------------------
-- 3. TABELA SOURCES (Origem dos dados)
-- -----------------------------------------------------------------------------
create table public.sources (
  id bigint generated by default as identity primary key,
  platform text check (platform in ('Facebook', 'Twitter', 'Instagram', 'NewsPortal', 'Other')) not null,
  name text not null, -- Ex: "Grupo Viva Tatuapé"
  base_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Segurança (RLS) para Sources
alter table public.sources enable row level security;

create policy "Fontes são públicas para leitura"
  on public.sources for select
  to authenticated
  using ( true );


-- -----------------------------------------------------------------------------
-- 4. TABELA INTENT_SIGNALS (O coração do sistema - Leads)
-- -----------------------------------------------------------------------------
create table public.intent_signals (
  id bigint generated by default as identity primary key,
  source_id bigint references public.sources(id) not null,
  location_id bigint references public.locations(id), -- Pode ser null se não identificar o bairro
  
  raw_content text not null, -- O texto do post
  url_original text not null, -- Link direto para o post
  
  price_min numeric, -- Opcional, se detectado
  price_max numeric, -- Opcional, se detectado
  
  posted_at timestamp with time zone not null, -- Data original do post
  scraped_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Índices para performance
create index intent_signals_location_id_idx on public.intent_signals(location_id);
create index intent_signals_posted_at_idx on public.intent_signals(posted_at desc);

-- Segurança (RLS) para Intent Signals
alter table public.intent_signals enable row level security;

create policy "Sinais são públicos para leitura"
  on public.intent_signals for select
  to authenticated
  using ( true );

-- Nenhuma policy de escrita. Apenas o Backend (via service key) irá popular esta tabela.


-- -----------------------------------------------------------------------------
-- 5. TABELA SAVED_SIGNALS (Interação do Corretor)
-- Tabela Pivô entre Profile e Intent Signals
-- -----------------------------------------------------------------------------
create table public.saved_signals (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  signal_id bigint references public.intent_signals(id) not null,
  
  status text check (status in ('saved', 'contacted', 'discarded')) default 'saved',
  notes text,
  
  saved_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, signal_id) -- Impede salvar o mesmo lead duas vezes
);

-- Segurança (RLS) para Saved Signals (CRÍTICO)
alter table public.saved_signals enable row level security;

create policy "Usuários gerenciam apenas seus próprios salvamentos"
  on public.saved_signals for all
  to authenticated
  using ( auth.uid() = user_id )
  with check ( auth.uid() = user_id );
